### ISSUE TITLE
error when signing up/error handling

### ISSUE THREAD

**Issue by lisahns** [fac25/bookbrooch#78]
when i signed up i got this error and the site broke for me

![Screenshot from 2022-11-16 16-35-48](https://user-images.githubusercontent.com/92580887/202246483-5267b0a9-a2f4-4a6a-a95c-1f2eac685d0b.png)

i restarted the server and closed & opened the browser and its working fine, but anytime I try to access the dashboard or logout, login, i get the same error again and the site breaks
Not sure where its coming from, seems a firebase thing :upside_down_face: 
even if you can't identify where the error is coming from, maybe some sort of error handling, that if something goes wrong with singing up the site is still useable?

**Comment by flare-s** [comment]
Thanks Lisa!
