### ISSUE TITLE
suggestion: getStaticProps for game??

### ISSUE THREAD

**Issue by lisahns** [fac25/bookbrooch#81]
I'm sure you've considered this, so let me know why this might not work for the game page. 
When playing the game it's loading a bit beforehand, and the animation is really nice, but would it maybe be possible to fetch all the data inside getStaticProps on the page file, then the website will fetch all the data on build-time and you would save some waiting/rendering time?
unless you have very small api restrictions like us lol

**Comment by modanova** [comment]
Thanks Lisa, we implemented getServerSideProps.
