### ISSUE TITLE
Selecting a page (Mobile 🍔 ) 

### ISSUE THREAD

**Issue by Joe-Lindie** [fac25/bookbrooch#85]
<img width="421" alt="Screenshot 2022-11-16 at 17 26 13" src="https://user-images.githubusercontent.com/92725856/202250764-b4964ea6-c3f8-4478-a063-82b7a58e038b.png">

When you select a page on the mobile layout, is there a way to have the mobile 🍔 menu retract? Currently, after selecting a page you have to manually click the `x` to close the menu.

**Comment by flare-s** [comment]
Thanks Joe! that was a really good advice.
